[package]
name = "zerorec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"
serde = "1.0.166"
itertools = "0.12.0"
nng = "1.0.1"
rmp-serde = "1.1.2"
simple-pagerank = "0.2.0"
